Completed css-canvas-medical.
Alex-Davis0/rc1121-code-solutions pull request #23
Opened 2021-12-05 23:27 UTC by Alex-Davis0

![css ](https://user-images.githubusercontent.com/93169087/144768285-2565f13e-15c8-4ea0-a371-6b75e547b48f.gif)

2021-12-06 18:42 UTC, Zhiwutian requested changes
overall look is solid, but I would refactor using columns and rows and flex. Position absolute should not be used to position elements on many sections of a page, it is best used only sparingly and not as part of a layout. Let me know if you have questions on the refactor!

2021-12-06 18:42 UTC, Zhiwutian commented on css-canvas-medical/styles.css
> +  position: absolute;
absolute will work here, but I would consider setting flex on the parent element so that you can use flexbox to position the nav as needed.

2021-12-06 18:42 UTC, Zhiwutian commented on css-canvas-medical/styles.css
> +  left: 43.7rem;
remember when using absolute positioning, you dont have to push from the original location. right should work well here.

2021-12-08 04:39 UTC, Alex-Davis0 commented
![css ](https://user-images.githubusercontent.com/93169087/145149185-63698251-26b6-4292-8ee5-7fd005787ab6.gif)

2021-12-08 04:41 UTC, Zhiwutian approved these changes
👍🏼

2021-12-08 04:41 UTC, merged