Completed express-post-json
Alex-Davis0/rc1121-code-solutions pull request #95
Opened 2022-01-25 23:48 UTC by Alex-Davis0

![Screenshot 2022-01-25 154606](https://user-images.githubusercontent.com/93169087/151078824-881bb8f6-f2d2-4926-ae92-6af0d87c89f5.png)
![Screenshot 2022-01-25 154624](https://user-images.githubusercontent.com/93169087/151078826-47f26dab-0fa9-4a19-b72a-1fd49b80f2a5.png)

2022-01-25 23:55 UTC, scbowler requested changes
Looking good, just missed one thing. Let me know if you have any questions.

2022-01-25 23:55 UTC, scbowler commented on express-post-json/index.js
> +  res.sendStatus(201);
Here you want to send back the newly created `grade` to the client.

2022-01-26 00:02 UTC, Alex-Davis0 commented
![Screenshot 2022-01-25 154624](https://user-images.githubusercontent.com/93169087/151080195-47347e23-7859-4296-ad50-cd3ca2931a97.png)
![Screenshot 2022-01-25 160117](https://user-images.githubusercontent.com/93169087/151080196-a6984529-eebb-47fe-95ff-1c285eaf07dc.png)

2022-01-26 00:10 UTC, scbowler approved these changes
Looks good! 👍

2022-01-26 00:10 UTC, merged