COmpleted
Alex-Davis0/rc1121-code-solutions pull request #96
Opened 2022-01-26 22:36 UTC by Alex-Davis0

![delete 404](https://user-images.githubusercontent.com/93169087/151258592-14776a33-77c2-44b8-9c8c-b8216d17cc3a.png)
![delete](https://user-images.githubusercontent.com/93169087/151258594-f3c3ba30-9f8c-4b75-b1a3-b55a90a95cac.png)
![delete 400](https://user-images.githubusercontent.com/93169087/151258597-a621bd60-bdf5-434d-9be0-40560c786343.png)
![get id](https://user-images.githubusercontent.com/93169087/151258611-3c0b5bb0-5e9a-40c8-a890-33b2f4ab956b.png)
![get](https://user-images.githubusercontent.com/93169087/151258615-9fec06d4-6a59-4976-a7c6-c500725565fc.png)
![post 400](https://user-images.githubusercontent.com/93169087/151258618-94c4f60a-85a5-4e29-bbaf-cbf92e770839.png)
![post](https://user-images.githubusercontent.com/93169087/151258619-686d5c2f-58d1-442b-9df8-828a35af90d8.png)
![put 400](https://user-images.githubusercontent.com/93169087/151258622-e37c3f56-52ab-441a-b3fd-993d9651308c.png)
![put 404](https://user-images.githubusercontent.com/93169087/151258624-4795d0b7-7726-48d4-847c-2a7954d01cfd.png)
![put](https://user-images.githubusercontent.com/93169087/151258626-f3e1ebc8-104a-4533-af72-1faa573b6e64.png)
![get id 400](https://user-images.githubusercontent.com/93169087/151258627-81e53d80-8202-4851-af27-29dce2e4753a.png)
![get id 404](https://user-images.githubusercontent.com/93169087/151258630-3dca4dd3-08eb-411f-978f-c17a881dcd41.png)

2022-01-26 22:59 UTC, scbowler requested changes
Looking good, just some cleanup items needed.

2022-01-26 22:59 UTC, scbowler commented on express-notes-api/index.js
> +  res.sendStatus(200);
You want to set the status and send the response on a single line. This is actually an oops it worked. Also by default the status code is `200` so if you want to send a 200 response you don't need to set that. 

You just need:
```JAVASCRIPT
res.json(arr);
```

2022-01-26 22:59 UTC, scbowler commented on express-notes-api/index.js
> +    res.status(200).json(notes[id]);
This is formatted good, but you don't need to set the code if it is `200`. So here this would be better:

```JAVASCRIPT
res.json(notes[id]);
```

2022-01-26 22:59 UTC, scbowler commented on express-notes-api/index.js
> +    res.status(400).json({ error: 'id must be a positive integer' });
The check for `!body.content` can give a misleading error, if there is no `content` property the client will get an error saying "id must be a positive integer" which doesn't fit. There should be a separate `else if` statement to check for `content` so you can give a better error response.

2022-01-26 22:59 UTC, scbowler commented on express-notes-api/index.js
> +  } else if (!notes[id].content) {
Here you don't need to check the content property, just if there is a value at `notes[id]`, checking the `content` property might even cause an error here in some circumstances.

```JAVASCRIPT
} else if (!notes[id]) {
```

2022-01-26 22:59 UTC, scbowler commented on express-notes-api/index.js
> +      res.status(200).json();
Here you should be sending back the updated note to the client:

```JAVASCRIPT
res.json(notes[id]);
```

2022-01-26 23:09 UTC, Alex-Davis0 commented
![put new](https://user-images.githubusercontent.com/93169087/151262364-f9ef217b-eb37-4ead-bde4-6cbe1cbfb05a.png)

2022-02-01 20:09 UTC, scbowler approved these changes
Looks good! 👍

2022-02-01 20:09 UTC, merged